report_header_info:
  - Application: "RosHAB Project"
  - Application Type: "Environmental Genomics"
  - Technology: "Oxford Nanopore Technologies (ONT) long reads"

show_analysis_paths: False
show_analysis_time: False

kraken:
  top_n: 10

skip_generalstats: true

custom_plot_config:
  nanostat_quality_dist:
    cpswitch_c_active: False
  kraken-top-n-plot:
    cpswitch_c_active: False

top_modules:
  - nanostat
  - kraken
